### ISSUE TITLE
Illegal instruction encountered

### ISSUE THREAD

**Issue by shaobo-he** [SRI-CSL/yices2#120]
Hello,
I attempted to run the pre-built binary of yices2 at http://yices.csl.sri.com/ on 64-bit Linux on an Intel E5-4620 processor. It failed with an "Illegal instruction" exception which my colleague suggests is due to the binary being compiled with AVX2 instructions.

Any help would be appreciated.

Thanks,
Shaobo

**Comment by BrunoDutertre** [comment]
That's a known problem. The fix is to build Yices from the source yourself.

Bruno

**Comment by shaobo-he** [comment]
Thank you for your reply. Is there a particular reason why Yices release is built in this way? For binary releases of other SMT solvers, I rarely see this issue.

**Comment by BrunoDutertre** [comment]
It's a side-effect of building GMP from source (as I do for Yices) and statically linking
GMP with Yices. I didn't notice it could be a problem for other people. Rebuilding GMP
again in a way that's portable is a pain and since it's easy for people to build Yices from
the source I haven't considered revisiting this.
