### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by BrunoDutertre** [SRI-CSL/yices2#69]
Sam is building a python binding to the Yices API.

How should we integrate this to the github repository?

Options we discussed:
1) start a new temporary branch for the python development
2) do everything in the master branch (as long as we keep the
    python stuff isolated in a separate directory).

Also, how do we organize the code:
1) a new directory 'bindings/python' (with options for future extensions)
    at the top level.
2) a special directory inside 'src' or 'src/api' or whatever.

**Comment by dddejan** [comment]
Branch sounds good, just to make sure that the build system on master is stable. 

For the code organization, bindings/python sounds good. That way it's easier to ensure it is separate and only uses the public Yices API.

The python API is also a great way to test the C API, so we can start using it for tests too.

I'm assuming the target is Python 2.7. Since it's hard to go back once it's done, it would be good if the bindings are made so that it's not too hard to move to Python 3 when needed later. This might be just wishful thinking, I don't know enough about 2.7 vs 3.
