### ISSUE TITLE
Question: are prebuild releases being made?

### ISSUE THREAD

**Issue by pjljvandelaar** [SRI-CSL/yices2#78]
At https://github.com/SRI-CSL/yices2/releases the latest release doesn't have prebuild executables like earlier versions (see e.g. version 2.5.2). 
Are the prebuild executables currently being made?
If so, when will they become available?

**Comment by maelvalais** [comment]
One idea to produce these Windows/Mac/Linux binaries could be to rely on continuous integration (typically travis-ci for linux and mac, appveyor for windows) that would, on every new tag, push the binaries as github uploads (that's what [I do](https://github.com/touist/touist/releases)).

Really conviennent as soon as the `.travis.yml` and `appveyor.yml` files have been written (this step may take some tries) because everything is automatic!!!

**Comment by ianamason** [comment]
Yes they are still being made, though we are currently revising things.
I think the latest builds are here:  http://yices.csl.sri.com/
Let me know if they are not.
